tools/pyot-icsi/pyot/urls.py
'''
Copyright (C) 2012,2013 Scuola Superiore Sant'Anna (http://www.sssup.it)
and Consorzio Nazionale Interuniversitario per le Telecomunicazioni
(http://www.cnit.it).

This file is part of PyoT, an IoT Django-based Macroprogramming Environment.

PyoT is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PyoT is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with PyoT.  If not, see <http://www.gnu.org/licenses/>.

@author: Andrea Azzara' <a.azzara@sssup.it>
'''
from django.conf.urls import patterns, include, url
from django.contrib import admin

from pyot import views
import settings


# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', views.home, name='home'),
    url(r'^settings/', views.settings, name='settings'),
    url(r'^startServer/(?P<wid>\d*)', views.startServer),
    url(r'^stopServer/(?P<wid>\d*)', views.stopServer),
    url(r'^getServerStatus', views.getServerStatus),
    url(r'^hostsList', views.hostsList, name='hostsList'),
    url(r'^hosts', views.hosts, name='hosts'),
    url(r'^resources', views.resources, name='resources'),
    url(r'^connectivity', views.pingPage, name='connectivity'),
    url(r'^resourceList', views.resourceList),
    url(r'^resource/(?P<rid>\d*)', views.resourcePage),
    url(r'^resourceStatus/(?P<rid>\d*)', views.resourceStatus),
    url(r'^opRes', views.opRes),
    url(r'^observe', views.observe),
    url(r'^obsList', views.obsList),
    url(r'^obsLast/(?P<rid>\d*)/', views.obsLast),
    url(r'^subList/(?P<rid>\d*)/', views.subList),
    url(r'^remHandler/(?P<hid>\d*)/', views.remHandler),
    url(r'^cancelSub/', views.cancelSub),
    url(r'^handlers/', views.handlers, name='handlers'),
    url(r'^startPing/(?P<hid>\d*)', views.startPing),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('django.contrib.auth.urls')),
)

urlpatterns += patterns(
    '',
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}),
)
urlpatterns += patterns(
    '',
    url(
        r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}
    ),
)


urlpatterns += patterns('pyot.views.rest',
    url(r'^api/networks/$', 'getWSNetworks'),
    url(r'^api/hosts/$', 'getWSNHosts'),
    url(r'^api/host/$', 'getWSNHost'),
    url(r'^api/wsndiscover/$', 'WSNDiscover'),
    url(r'^api/getresource/$', 'getResource'),
)

tools/pyot-icsi/pyot/models/misc.py
'''
Copyright (C) 2012,2013 Scuola Superiore Sant'Anna (http://www.sssup.it)
and Consorzio Nazionale Interuniversitario per le Telecomunicazioni
(http://www.cnit.it).

This file is part of PyoT, an IoT Django-based Macroprogramming Environment.

PyoT is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PyoT is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with PyoT.  If not, see <http://www.gnu.org/licenses/>.

@author: Andrea Azzara' <a.azzara@sssup.it>
'''

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save


TFMT = settings.TFMT
LOG_CHOICES = (
    (u'registration', u'registration'),
    (u'clean', u'clean'),
    (u'discovery', u'discovery'),
    (u'ghost', u'ghost'),
    (u'RdRetry', u'RdRetry'),
    (u'RdRec', u'RdRec'),
    (u'SubRec', u'SubRec'),
)


class UserProfile(models.Model):
    '''
    Custom user profile model including an 'organization' field.
    '''
    user = models.ForeignKey(User, unique=True, related_name='profile')
    organization = models.CharField(max_length=50, blank=False)

    def save(self, *args, **kwargs):
        try:
            existing = UserProfile.objects.get(user=self.user)
            self.id = existing.id # force update instead of insert
        except UserProfile.DoesNotExist:
            pass
        models.Model.save(self, *args, **kwargs)

    class Meta(object):
        app_label = 'pyot'


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class Log(models.Model):
    '''
    Defines a model to store several type of log messages in the db.
    '''
    log_type = models.CharField(max_length=30, choices=LOG_CHOICES)
    message = models.CharField(max_length=1024)
    timeadded = models.DateTimeField(auto_now_add=True, blank=True)

    def __unicode__(self):
        return u"{t} {log_type} {message}".format(log_type=self.log_type,
                                                  message=self.message,
                                                  t=self.timeadded.strftime(TFMT))

    class Meta(object):
        app_label = 'pyot'

tools/pyot-icsi/pyot/views/general.py
'''
Copyright (C) 2012,2013 Scuola Superiore Sant'Anna (http://www.sssup.it) 
and Consorzio Nazionale Interuniversitario per le Telecomunicazioni 
(http://www.cnit.it).

This file is part of PyoT, an IoT Django-based Macroprogramming Environment.

PyoT is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
  
PyoT is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
 
You should have received a copy of the GNU General Public License
along with PyoT.  If not, see <http://www.gnu.org/licenses/>.

@author: Andrea Azzara' <a.azzara@sssup.it>
'''
from django.shortcuts import render


def home(request):
    return render(request, 'home.htm')

tools/pyot-icsi/pyot/views/rest.py
'''
Copyright (C) 2012,2013 Scuola Superiore Sant'Anna (http://www.sssup.it)
and Consorzio Nazionale Interuniversitario per le Telecomunicazioni
(http://www.cnit.it).

This file is part of PyoT, an IoT Django-based Macroprogramming Environment.

PyoT is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

PyoT is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with PyoT.  If not, see <http://www.gnu.org/licenses/>.

@author: Andrea Azzara' <a.azzara@sssup.it>
'''
import json
import logging

from celery.result import AsyncResult
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.core.paginator import Paginator
from django.core.urlresolvers import reverse
from django.db.models import Max
from django.http import HttpResponseBadRequest
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import HttpResponse, render
from django.template import Context
from django.views.decorators.csrf import csrf_exempt

from pyot.Forms import *
from pyot.models import *
from pyot.resourceRepr import getRenderer
from pyot.tasks import *
from pyot.tools.utils import *

from rest_framework.renderers import JSONRenderer
from rest_framework.parsers import JSONParser
from rest_framework import serializers


# @staff_member_required
def startServer(request, wid):
    try:
        net = Network.objects.get(id=wid)
        if net.pid:
            return HttpResponse("Already running")
        else:
            net.startRD()
            return HttpResponse("Started")
    except ObjectDoesNotExist:
        msg = 'worker is not in db'
        return HttpResponse(msg)


# @staff_member_required
def stopAllSubs():
    sublist = Subscription.objects.filter(active=True)
    # stop all active subscriptions
    for s in sublist:
        s.cancel_subscription()

# @staff_member_required
def stopServer(request, wid):
    logging.debug('stopping')
    try:
        net = Network.objects.get(id=wid)
        if not net.pid:
            return HttpResponse("not running")
        else:
            stopAllSubs()
            net.stopRD()

        all_hosts = Host.objects.all()
        for host in all_hosts:
            host.keepAliveCount = 0
            host.save()

        return HttpResponse("revoked")
    except ObjectDoesNotExist:
        return HttpResponse("No process to stop")
    except Exception:
        pass

def getServerStatus(request):
    if request.method != 'GET':
        response = 'Bad request, needs a GET method'
        return HttpResponseBadRequest(response)
    networks = Network.objects.all()
    status = get_celery_worker_status()
    l = []
    for net in networks:
        Id = str(net.id)
        host = net.hostname
        prefix = str(net.network)
        if net.pid:
            rstatus = AsyncResult(net.pid).status
        else:
            rstatus = 'not running'
        try:
            _e = status[host]
            wstatus = 'Connected'
            uriLink = '<input type="submit" value="START" onclick = "startCoap(' + Id + ');"/><input type="submit" value="STOP" onclick = "stopCoap(' + Id + ');"/>'
        except KeyError:
            wstatus = 'Disconnected'
            uriLink = ''
        sub = [host, prefix, uriLink, wstatus, rstatus]
        dic = {'cell': sub}
        l.append(dic)
    json_dict = {
        'page': 1,
        'total': 1,
        'rows': l
        }
    j = json.dumps(json_dict)
    return HttpResponse(j)


# @login_required
def hosts(request):
    return render(request, 'host_list.htm')


# @login_required
def hostsList(request):
    if request.method != 'GET':
        response = 'Bad request, needs a GET method'
        return HttpResponseBadRequest(response)
    sortname = request.REQUEST.get('sortname', 'timeadded')
    sortorder = request.REQUEST.get('sortorder', 'asc')  # Ascending/descending
    page = request.REQUEST.get('page', 1)  # What page we are on
    rp = int(request.REQUEST.get('rp', 15))  # Num requests per page
    order = ''
    if sortorder == 'desc':
        order = '-'
    obj = Host.objects.filter(active=True).values('id', 'ip6address', 'timeadded', 'lastSeen').order_by(order + sortname)
    p = Paginator(obj, rp)
    filteredHostList = p.page(page).object_list
    l = []
    for i in filteredHostList:
        Id = str(i['id'])
        date = i['timeadded'].strftime('%d %b %Y %H.%M:%S')
        lastSeen = i['lastSeen'].strftime('%d %b %Y %H.%M:%S')

        sub = [Id, i['ip6address'], date, lastSeen]
        dic = {'id': Id, 'cell': sub}
        l.append(dic)
    json_dict = {
        'page': page,
        'total': p.count,
        'rows': l
        }
    j = json.dumps(json_dict)
    return HttpResponse(j)

# @login_required
def resources(request):
    hostid = request.REQUEST.get('id', '')

    if hostid == '':
        logging.debug('vuoto')
        allres = Host.objects.filter(active=True)
        if len(allres) > 0:
            j = 0
            out = ''
            for i in allres:
                if j != 0:
                    out = out + ',' + str(i.id)
                else:
                    out = out + str(i.id)
                j += 1
            hostid = out
    c = Context({'listVar': hostid})
    return render(request, 'resource_list.htm', c)


# @login_required
def resourceList(request):
    hostidList = None
    query = request.REQUEST.get('query', '')
    querytype = request.REQUEST.get('qtype', '')
    page = request.REQUEST.get('page', 1)  # What page we are on
    rp = int(request.REQUEST.get('rp', 15))  # Num requests per page

    if querytype == 'id' and query != '':
        hostidList = query.split(',')
    if hostidList == None:
        return HttpResponse('')
    for i in hostidList:
        logging.debug('retrieving resource ' + i)
    resObj = Resource.objects.filter(host__id__in=hostidList,
                                     host__active=True)  # eccezioni per la query
    p = Paginator(resObj, rp)
    filteredResList = p.page(page).object_list
    l = []
    for i in filteredResList:
        Id = str(i.id)
        uriLink = '<div class="fake_link" onclick = "gotoRes(' + Id + ');">' + i.uri + '</div >'
        sub = [Id, uriLink, str(i.host.ip6address), i.title]
        dic = {'id': Id, 'cell': sub}
        l.append(dic)
    json_dict = {
        'page': page,
        'total': p.count,
        'rows': l
        }
    j = json.dumps(json_dict)
    return HttpResponse(j)

# @login_required
def resourcePage(request, rid):
    try:
        r = Resource.objects.get(id=rid)
    except Resource.DoesNotExist:
        raise Http404
    resObj = getRenderer(r)
    c, t = resObj.getTemplate(request)
    return render(request, t, c)

def resourceStatus(request, rid):
    try:
        # rid =self.kwargs['rid']
        r = Resource.objects.get(id=rid)
        if r.host.active == True:
            status = "CONNECTED"
        else:
            status = "DISCONNECTED, last seen on: " + r.host.lastSeen.strftime(TFMT)
        return HttpResponse(status)
    except Resource.DoesNotExist:
        resp = 'The resource with id= ' + str(rid) + ' does not exist anymore'
        return HttpResponse(resp)


# @login_required
def obsList(request):
    rid = request.GET['query']
    sortname = request.REQUEST.get('sortname', 'timeadded')
    sortorder = request.REQUEST.get('sortorder', 'asc')  # Ascending/descending
    page = request.REQUEST.get('page', 1)  # What page we are on
    rp = int(request.REQUEST.get('rp', 15))  # Num requests per page
    order = ''
    if sortorder == 'desc':
        order = '-'
    messList = CoapMsg.objects.filter(resource__id=rid).exclude(sub=None).order_by(order + sortname)
    p = Paginator(messList, rp)
    filteredMessList = p.page(page).object_list
    l = []
    for i in filteredMessList:
        Id = str(i.id)
        date = i.timeadded.strftime('%d %b %Y %H.%M:%S')
        sub = [Id, date, i.payload]
        dic = {'id': Id, 'cell': sub}
        l.append(dic)
    json_dict = {
        'page': page,
        'total': p.count,
        'rows': l
        }
    j = json.dumps(json_dict)
    return HttpResponse(j)


# @staff_member_required
def settings(request):
    return render(request, 'settings.htm')

def obsLast(request, rid):
    try:
        s = Subscription.objects.filter(resource__id=rid, active=True).values('id').iterator()
        a = []
        for i in s:
            a.append(i['id'])
            logging.debug(i)

        maxID = CoapMsg.objects.filter(resource=rid, sub__in=a).aggregate(Max('id'))
        lastMsg = CoapMsg.objects.get(resource=rid, id=maxID['id__max'])
        r = lastMsg.payload
    except (ObjectDoesNotExist, MultipleObjectsReturned):
        r = 'none'
    return HttpResponse(r)



# @login_required
def subList(request, rid):
    try:
        sub = Subscription.objects.filter(resource__id=rid, active=True)
        if sub.count():
            active = True
        else:
            active = False
        c = Context({'subList': sub, 'active': active})
        return render(request, 'sub_list.htm', c)
    except Subscription.DoesNotExist:
        raise Http404


# @staff_member_required
def cancelSub(request):
    pid = request.REQUEST.get('pid', '')
    try:
        s = Subscription.objects.get(pid=pid)
        s.cancel_subscription()
        return HttpResponse('ok task revoked')
    except Subscription.DoesNotExist:
        raise Http404


# @login_required
def opRes(request):
    try:
        rid = request.REQUEST.get('id', '')
        payload = request.REQUEST.get('pd', None)
        operation = request.REQUEST.get('op', '')

tools/pyot-icsi/pyot/templates/account.html
{% extends "base.htm" %}


{% block title %}My Account{% endblock %}
{% block h1 %} <h1>My Account</h1>{% endblock %}
{% block content %}

<p>If you want to change your password, clic <a href="/password_change">here</a>.</p>

<p>To delete your account, clic <a href="{% url deleteuser %}">here</a>.</p>


{% endblock %}

tools/pyot-icsi/pyot/templates/base.htm
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<link rel="stylesheet" type="text/css" href="/static/style.css">
	<link rel="stylesheet" type="text/css" href="/static/flexigrid.css">
	<link rel="stylesheet" type="text/css" href="/static/tablestyle.css">
	<script src="/static/jquery-1.8.2.min.js"></script>
	
	<script type="text/javascript" src="/static/flexigrid.js"></script>
	<script type="text/javascript" src="/static/smartupdater.4.0.beta.js"></script>
	
{% block includes %}{% endblock %}

	<head>
		<title>{% block title %}Hello world!{% endblock %}</title>
	</head>
	<body>


	
	<div id="wrap">
	{% block h1 %}
		<h1>Base Template</h1>
	{% endblock %}	
		<ul id="nav">
	      <li><a href="{% url "home" %}">PyoT</a></l>
	      <li><a href="{% url "hosts" %}">Hosts</a></li>
	      <li><a href="{% url "resources" %}">Resources</a></li>
	      <li><a href="{% url "handlers" %}">Handlers</a></li>
	      <li><a href="{% url "settings" %}">Settings</a></li>
	      <li><a href="{% url "connectivity" %}">Test Ping</a></li>
	      <li><a href="http://127.0.0.1:8888" target="_blank">Notebook</a></li>
	      <li><a href="/admin" target="_blank">Admin</a></li>


   		</ul>
	
		<div id="content">
		{% block h %}{% endblock %}
		{% block content %}{% endblock %}
		{% block extra %}{% endblock %}
		</div>
		</div>
		<div id="bottom" style= "position:relative;">

	<a href="http://www.cnit.it/">
		<img src="/static/images/cnit.png" height="50" width="90" style="position: absolute; left:70px; top:20px">
	</a>
	<a href="http://www.sssup.it/">
		<img src="/static/images/SSSA.jpg" height="80" width="80" style="position: absolute; left:330px; top:10px">
	</a>
	<a href="http://retis.sssup.it/">			
		<img src="/static/images/Retis.png" height="50" width="90" style="position: absolute; left:600px; top:20px">
	</a>
		</div>
	</body>
</html>

tools/pyot-icsi/pyot/templates/contacts.htm
{% extends "base.htm" %}
{% block title %}Contacts{% endblock %}
	
	{% block h1 %}<h1>Contacts</h1>{% endblock %}
{% block content %}

<h3>Please, send us comments or... whatever</h3>

<form action="/contacts/" method="post"> {% csrf_token %}
    {{ form.non_field_errors }}
    <p class="fieldWrapper">
        {{ form.subject.errors }}
        <label for="id_subject">Email subject:</label>
        {{ form.subject }}
    </p>
    <p class="fieldWrapper">
        {{ form.message.errors }}
        <label for="id_message">Your message:</label>
        {{ form.message }}
    </p>
    <p class="fieldWrapper">
        {{ form.sender.errors }}
        <label for="id_sender">Your email address:</label>
        {{ form.sender }}
    </p>
    <p><input type="submit" value="Send message" /></p>
</form>


{% endblock %}

tools/pyot-icsi/pyot/templates/deleteuser.htm
{% extends "base.htm" %}
{% block title %}Delete User?{% endblock %}
	
	{% block h1 %}<h1>Deleting User...</h1>{% endblock %}
{% block content %}


<p>Are you really sure?? </p>
<p><a href="{% url confirmdeleteuser %}">Yes, I am.</a></p>


{% endblock %}

tools/pyot-icsi/pyot/templates/handlers.htm
{% extends "base.htm" %}
{% block title %}Event Handlers{% endblock %}

{% block h1 %}<h1>Event Handlers</h1>{% endblock %}

{% block content %}

	{% if msghandlers %}
		<h2>Current Message handlers</h2>
	<table id="hor-minimalist-a">
	    <tr>
		    <th>ID</th>
		    <th>Description</th>
		    <th>Activation Count</th>
		    <th>Max Activations Limit</th> 
		    <th>Remove Handler</th> 
	    </tr>
    {% for msghandler in msghandlers %}
        <tr>
        <td>{{ msghandler.id }}</td>
        <td>{{ msghandler.description }}</td>
        <td>{{ msghandler.activationCount }}</td>
        <td>{{ msghandler.max_activations }}</td>
        <td><a href="/remHandler/{{ msghandler.eventhandler_ptr.id}}/">Remove</a></td>
        </tr>
    {% endfor %}
    </table>
	{% endif %}	

<!-- 	{% if codehandlers %}
		<br> Code handlers <br>
	    <ul>
	    {% for codehandler in codehandlers %}
	        <li>
	        {{ codehandler.id }} , {{ codehandler.description }}, {{ codehandler.activationCount }}, {{ codehandler.max_activations }}
			<a href="/remHandler/{{ codehandler.eventhandler_ptr.id}}/">Remove Handler</a>	       
	        </li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No Code handlers </p>
	{% endif %}	
	
	
	----------------------------------- -->

<!-- 	<br>Code Event Form
<form action="{% url "handlers" %}" method="post" enctype="multipart/form-data">
    {{ codeForm.as_p }}
    <input type="submit" value="New" />
</form>	 

	----------------------------------- -->
	<div id="contact-area">	
		<h3>Create Message Event Handler</h3>
		<form action="{% url "handlers" %}" method="post" enctype="multipart/form-data"> {% csrf_token %}
		    {{ msgForm.as_p }}
		
		    <input type="submit" value="New"class="submit-button"  />
		</form>	
	</div>
<!-- 	-----------------------------------
	<br>Message Event Form, with frequency
<form action="{% url "handlers" %}" method="post" enctype="multipart/form-data">
    {{ msgFormFreq.as_p }}

    <input type="submit" value="New" />
</form>	 -->

<input type=button value="Previous Page" onClick="javascript:history.go(-1);">

{% endblock %}

tools/pyot-icsi/pyot/templates/home.htm
{% extends "base.htm" %}
{% block title %}Home{% endblock %}
	
	{% block h1 %}<h1>PyoT</h1>{% endblock %}
{% block content %}

<div>
	<p> PyoT is a Web-Based Macroprogramming Interface for the IoT</p>

	<img src="/static/images/pyotarch.png"  alt="PyoT's Architecture" width="500">

	<p>

	<ul align="left">
		<li>Allows remote management of IoT-based networks
		<li>CoAP resources and 6LoWPAN nodes are abstracted as high-level Python objects
		<li>Provides a web interface to interact with CoAP resources
		<li>Provides interactive Macroprogramming, using the Shell
		<li>Resource discovery and indexing based on CoRE Resource Directory
		<li>Flexible event handling (automatic reaction when IoT resources send alarm notifications)
		<li>Asynchronous tasks performing communication with IoT nodes on PyoT Workers

	</ul></p>
	<p>PyoT is available on <a href="https://github.com/tecip-nes/pyot">Github</a>.</p>
</div>
{% endblock %}

tools/pyot-icsi/pyot/templates/host_list.htm
{% extends "base.htm" %}
{% block title %}Host List{% endblock %}

	{% block h1 %}<h1>Host List</h1>{% endblock %}
	
{% block content %}


	<table id="hoststable" style="display:none"></table>

	<div class="feedback" id="feedback"> </div>
	<div class="ph" id="ph"></div>
	<script type="text/javascript" src="/static/list_common.js"></script>
	<script type="text/javascript" src="/static/host_list.js"></script>
	 
{% endblock %}

tools/pyot-icsi/pyot/templates/ping.htm
{% extends "base.htm" %}
	
{% block title %}Connectivity Test{% endblock %}
		{% block h1 %}<h1>Connectivity Test</h1>{% endblock %}
{% block content %}

	{% if hosts %}
	<select id = "host">	
    {% for host in hosts %}
        <option value="{{ host.id }}">{{ host.ip6address  }}</option> 
    {% endfor %}
	</select>
	<input type="submit" value="Ping"  onclick = "ping();"/>
	{% else %}
	<div id = "host"></div>
	{% endif %}	
	
	<textarea id="feedback" rows="8" cols="80" readonly></textarea>
	
	<script type="text/javascript">

	function setFeedback(msg){
		var separator = '****************\n';
		document.getElementById('feedback').value = msg + '\n' + separator + document.getElementById('feedback').value;
	}	

	function ping(id){
		var hostid = document.getElementById('host').value;
		$.ajax({
			type: "GET",
			url: "/startPing/" + hostid,
			success: function(msg){
			setFeedback(msg);
		}
		});
	}

	</script>

	
{% endblock %}

tools/pyot-icsi/pyot/templates/reslist.htm
{% if lista %}

<table class="rounded-corner">
	<thead>
		<tr>
			<th scope="col" class="rounded-company">ID</th>
			<th scope="col" class="rounded-q1">Host</th>
			<th scope="col" class="rounded-q1">URI</th>
		</tr>
	</thead>
{% for f in lista %}
	<tr>
		<td>{{ f.id}} </td>
		<td> {{f.host.ip6address}} </td>
		<td> {{f.uri}} </td>
	</tr>
{% endfor %}
</table>
{% endif %}

tools/pyot-icsi/pyot/templates/resource_list.htm
{% extends "base.htm" %}
{% block title %}Resource List{% endblock %}


	{% block h1 %}<h1>Resource List</h1>{% endblock %}
	
{% block content %}
	<script type="text/javascript" >var hostid = '{{ listVar }}';</script>

	<div><table id="resourcetable" style="display:none"></table></div>

	<div class="feedback" id="feedback"></div>
	<script type="text/javascript" src="/static/list_common.js"></script>
	<script type="text/javascript" src="/static/resources_list.js"></script>
	 
{% endblock %}

tools/pyot-icsi/pyot/templates/sub_list.htm
{% if active %}

<table  id="hor-minimalist-a" style = "margin-left: auto; margin-right: auto;">
	<thead>
		<tr>
			<!--<th>Subscription type</th>
			<th>Threshold</th>-->
			<th>Duration</th>			
			<th>Timeadded</th>
			<th>PID</th>
			<th>Stop</th>
		</tr>
	</thead>
{% for f in subList %}
	<tr>
		<!--<td> {{ f.subtype }} </td>
		<td> {{ f.threshold }} </td>-->
		<td> {{ f.duration }} </td>		
		<td> {{ f.timeadded}} </td>
		<td> {{ f.pid}} </td>	
		<td> <div class="fake_link" onclick = "terminate('{{f.pid}}');"> Stop task </div ></td>
	</tr>
{% endfor %}
</table>
{% else %}
No active subscriptions
{% endif %}

tools/pyot-icsi/pyot/templates/thanks.htm
{% extends "base.htm" %}
{% block title %}Thanks{% endblock %}
	
	{% block h1 %}<h1>Thanks</h1>{% endblock %}
{% block content %}

Thanks for sending your comments.

{% endblock %}